#Crop growth multiplier on farmland, this value multiplies the default vanilla growth rate.
#Example: 10.5 -> Ten and a half times the speed of vanilla crop growth.
#Range: 0.0 ~ 25.0
tilledSoilMultiplier = 0.5
#Crop growth multiplier on tilled end stone, this value multiplies the default vanilla growth rate.
#Example: 10.5 -> Ten and a half times the speed of vanilla crop growth.
#Range: 0.0 ~ 25.0
tilledEndMultiplier = 1.0
#Enable tilling End stone.
#Disabling this does not remove the Tilled End Stone block, only the creation of it.
tilledEndStone = true
#Chance of spawning an Endermite when a fully grown Ender Crop grown on Tilled End Stone is harvested.
#Example: 10 -> 1 in 10 chance. 0 to disable.
#Range: > 0
miteChance = 50
#Require a hoe to be enchanted with Unbreaking (I) to till End stone.
endstoneNeedsUnbreaking = true

